project:
  useAWS: false # bool, set to true if using AWS, set false and ignore all AWS entries
  awsSetup:
    bucket: # working bucket in AWS
    region: # working AWS region
    rootDomain: # a fully qualified domain name without 'https://'
    cpu: 2 # int 1,2, or 4
    memory: 10 # int 1-30

  events:
    startServerStep:  # int
    stopServerStep:  # int
  id: # Letters, Numbers and '-' only!
  live: True # bool
  maxRuntime: 60 # int in minutes.
  name: # str
  researcher: # str
  ssl:
    fullchain: SSL/fullchain.pem # path to fullchain.pem file excluding bucket name
    privkey: SSL/privkey.pem # path to privkey.pem file excluding bucket name
    sslBucket: # bucket name for resolving paths above
  steps: # any number of steps needed with corresponding filenames
    1: exampleConsent.html
    2:
    3:
    4:
    5:
    finalStep: # required, filename can be same as last numbered step
  teamMembers: # str
trial:
  actionBufferLifespan: 10 # int
  maxEpisodes: 20 # int
  game: GDY-Labyrinth-v0   #GDY-Labyrinth-v0 #GDY-Labyrinth-v0 #PongNoFrameskip-v4 #MountainCar-v0 # full environment name #parking-v0
  dataFile: trial # episode or trial
  s3upload: True
  actionSpace: # the appropriate action space for environment. Order matters
    - noop
    - left
    - up
    - right
    - down
    #- noop
    #- left
    #- right
    #- up
    #- down
    #- LEFT
    #- RIGHTFIRE
    #- LEFTFIRE
    #- downleft
  frameRateStepSize: 5 # int Optional if allowFrameRateChange = False
  minFrameRate: 1 # int Optional if allowFrameRateChange = False
  maxFrameRate: 90 # int Optional if allowFrameRateChange = False
  allowFrameRateChange: True # bool
  startingFrameRate: 40 # int Required
  pSet: 44
  ui: # to include ui button set to True, False buttons will not be shown
    left: True
    up: True
    right: True
    down: True
    start: True
    stop: True
    pause: False
    reset: False
    trainOffline: False
    trainOnline: False
    good: True
    reallygood: False
    bad: True
    fpsSet: True
    fpsUp: True
    fpsDown: True
    demonstration: True
    flag: False
    scaffolding: False
    fdsSet: False
    stop demonstration: True

